name: form_assist
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.9+5
  clipboard_manager: ^0.0.1
  firebase_ml_vision: 
  flushbar: ^1.9.1
  google_sign_in: any
  flutter_form_builder : 3.5.5
  speech_recognition: ^0.3.0+1
  flutter_tts: ^0.7.0
  flutter_spinkit: "^4.1.0"
  cupertino_icons: ^0.1.2
  permission_handler: '^4.0.0'
  http: 
  intro_views_flutter: 


dev_dependencies:
  flutter_test:
    sdk: flutter
  image_picker:


flutter:

  uses-material-design: true

  assets:
   - assets/
   - assets/images/
   - assets/explore/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato.ttf
    - family: BBPU
      fonts:
        - asset: fonts/BBPU.ttf
